version: '3.8'

services:
  leader:
    image: postgres:13
    container_name: db_leader
    volumes:
      - ./db/leader:/var/lib/postgresql/data
      - ./configs/wal_config.conf:/etc/postgresql/wal_config.conf
    environment:
      - POSTGRES_DB=distributed_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/etc/postgresql/wal_config.conf"]

  follower1:
    image: postgres:13
    container_name: db_follower1
    volumes:
      - ./db/follower1:/var/lib/postgresql/data
      - ./configs/wal_config.conf:/etc/postgresql/wal_config.conf
    environment:
      - POSTGRES_DB=distributed_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    depends_on:
      - leader
    command: ["postgres", "-c", "config_file=/etc/postgresql/wal_config.conf"]

  follower2:
    image: postgres:13
    container_name: db_follower2
    volumes:
      - ./db/follower2:/var/lib/postgresql/data
      - ./configs/wal_config.conf:/etc/postgresql/wal_config.conf
    environment:
      - POSTGRES_DB=distributed_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    depends_on:
      - leader
    command: ["postgres", "-c", "config_file=/etc/postgresql/wal_config.conf"]
